### ISSUE TITLE
Custom sets not working anymore

### ISSUE THREAD

**Issue by Michpem** [jake-white/VGC-2016-Damage-Calculator#6]
The custom sets aren't working anymore. After pasting the set in the box and clicking on the Save button, nothing happens. I reload the page, clear my cookies and stuff but nothing fixes it.

I'm using the latest Firefox, if that helps.

**Comment by jake-white** [comment]
Is there a specific Pokemon this is happening with? It seems to be working in the latest versions of Chrome and Firefox for me.

**Comment by Michpem** [comment]
It was happening with the Primals, but I see what's the issue: It doesn't recognize the name Kyogre-Primal, which is what I used in Showdown before importing the set. Sorry about that! I'll make sure to double check next time.

**Comment by jake-white** [comment]
I was wondering about that.  I understand, I use the primal versions in the editor as well so that I can easily see the stats while teambuilding.  So I've just added those as separate forms, and now when you enter Primal-Groudon/Kyogre, it will correct it to the standard version, and then primal evolve them when it detects a red/blue orb.

Thanks for the report, and let me know if you find any other issues.
